// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type GroupInitParameters struct {

	// ID of the application this group belongs to.
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// The channel this group provides.
	ChannelID *string `json:"channelId,omitempty" tf:"channel_id,omitempty"`

	// A description of the group.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of the group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// . Defaults to 1 minutes.
	// The maximum number of updates that can be performed within the `policy_period_interval`. Defaults to `9999999`.
	PolicyMaxUpdatesPerPeriod *float64 `json:"policyMaxUpdatesPerPeriod,omitempty" tf:"policy_max_updates_per_period,omitempty"`

	// .
	// Only update between 9am and 5pm. Defaults to `false`.
	PolicyOfficeHours *bool `json:"policyOfficeHours,omitempty" tf:"policy_office_hours,omitempty"`

	// . Defaults to 9999999.
	// Period used in combination with `policy_max_updates_per_period`. Defaults to `1 minutes`.
	PolicyPeriodInterval *string `json:"policyPeriodInterval,omitempty" tf:"policy_period_interval,omitempty"`

	// Safe mode will only update 1 instance at a time, and stop if an update fails. Defaults to `false`.
	PolicySafeMode *bool `json:"policySafeMode,omitempty" tf:"policy_safe_mode,omitempty"`

	// Timezone used to inform `policy_office_hours`.
	PolicyTimezone *string `json:"policyTimezone,omitempty" tf:"policy_timezone,omitempty"`

	// Timeout for updates Defaults to `60 minutes`.
	PolicyUpdateTimeout *string `json:"policyUpdateTimeout,omitempty" tf:"policy_update_timeout,omitempty"`

	// Enable updates. Defaults to `true`.
	PolicyUpdatesEnabled *bool `json:"policyUpdatesEnabled,omitempty" tf:"policy_updates_enabled,omitempty"`

	// Identifier for clients, filled with the group ID if omitted.
	Track *string `json:"track,omitempty" tf:"track,omitempty"`
}

type GroupObservation struct {

	// ID of the application this group belongs to.
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// The channel this group provides.
	ChannelID *string `json:"channelId,omitempty" tf:"channel_id,omitempty"`

	// Creation timestamp
	CreatedTS *string `json:"createdTs,omitempty" tf:"created_ts,omitempty"`

	// A description of the group.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// . Defaults to 1 minutes.
	// The maximum number of updates that can be performed within the `policy_period_interval`. Defaults to `9999999`.
	PolicyMaxUpdatesPerPeriod *float64 `json:"policyMaxUpdatesPerPeriod,omitempty" tf:"policy_max_updates_per_period,omitempty"`

	// .
	// Only update between 9am and 5pm. Defaults to `false`.
	PolicyOfficeHours *bool `json:"policyOfficeHours,omitempty" tf:"policy_office_hours,omitempty"`

	// . Defaults to 9999999.
	// Period used in combination with `policy_max_updates_per_period`. Defaults to `1 minutes`.
	PolicyPeriodInterval *string `json:"policyPeriodInterval,omitempty" tf:"policy_period_interval,omitempty"`

	// Safe mode will only update 1 instance at a time, and stop if an update fails. Defaults to `false`.
	PolicySafeMode *bool `json:"policySafeMode,omitempty" tf:"policy_safe_mode,omitempty"`

	// Timezone used to inform `policy_office_hours`.
	PolicyTimezone *string `json:"policyTimezone,omitempty" tf:"policy_timezone,omitempty"`

	// Timeout for updates Defaults to `60 minutes`.
	PolicyUpdateTimeout *string `json:"policyUpdateTimeout,omitempty" tf:"policy_update_timeout,omitempty"`

	// Enable updates. Defaults to `true`.
	PolicyUpdatesEnabled *bool `json:"policyUpdatesEnabled,omitempty" tf:"policy_updates_enabled,omitempty"`

	// Indicates whether a rollout is currently in progress for this group.
	RolloutInProgress *bool `json:"rolloutInProgress,omitempty" tf:"rollout_in_progress,omitempty"`

	// Identifier for clients, filled with the group ID if omitted.
	Track *string `json:"track,omitempty" tf:"track,omitempty"`
}

type GroupParameters struct {

	// ID of the application this group belongs to.
	// +kubebuilder:validation:Optional
	ApplicationID *string `json:"applicationId,omitempty" tf:"application_id,omitempty"`

	// The channel this group provides.
	// +kubebuilder:validation:Optional
	ChannelID *string `json:"channelId,omitempty" tf:"channel_id,omitempty"`

	// A description of the group.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of the group.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// . Defaults to 1 minutes.
	// The maximum number of updates that can be performed within the `policy_period_interval`. Defaults to `9999999`.
	// +kubebuilder:validation:Optional
	PolicyMaxUpdatesPerPeriod *float64 `json:"policyMaxUpdatesPerPeriod,omitempty" tf:"policy_max_updates_per_period,omitempty"`

	// .
	// Only update between 9am and 5pm. Defaults to `false`.
	// +kubebuilder:validation:Optional
	PolicyOfficeHours *bool `json:"policyOfficeHours,omitempty" tf:"policy_office_hours,omitempty"`

	// . Defaults to 9999999.
	// Period used in combination with `policy_max_updates_per_period`. Defaults to `1 minutes`.
	// +kubebuilder:validation:Optional
	PolicyPeriodInterval *string `json:"policyPeriodInterval,omitempty" tf:"policy_period_interval,omitempty"`

	// Safe mode will only update 1 instance at a time, and stop if an update fails. Defaults to `false`.
	// +kubebuilder:validation:Optional
	PolicySafeMode *bool `json:"policySafeMode,omitempty" tf:"policy_safe_mode,omitempty"`

	// Timezone used to inform `policy_office_hours`.
	// +kubebuilder:validation:Optional
	PolicyTimezone *string `json:"policyTimezone,omitempty" tf:"policy_timezone,omitempty"`

	// Timeout for updates Defaults to `60 minutes`.
	// +kubebuilder:validation:Optional
	PolicyUpdateTimeout *string `json:"policyUpdateTimeout,omitempty" tf:"policy_update_timeout,omitempty"`

	// Enable updates. Defaults to `true`.
	// +kubebuilder:validation:Optional
	PolicyUpdatesEnabled *bool `json:"policyUpdatesEnabled,omitempty" tf:"policy_updates_enabled,omitempty"`

	// Identifier for clients, filled with the group ID if omitted.
	// +kubebuilder:validation:Optional
	Track *string `json:"track,omitempty" tf:"track,omitempty"`
}

// GroupSpec defines the desired state of Group
type GroupSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GroupInitParameters `json:"initProvider,omitempty"`
}

// GroupStatus defines the observed state of Group.
type GroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Group is the Schema for the Groups API. A group provides a particular release channel to machines and controls various options that manage the update procedure.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nebraska}
type Group struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   GroupSpec   `json:"spec"`
	Status GroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GroupList contains a list of Groups
type GroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Group `json:"items"`
}

// Repository type metadata.
var (
	Group_Kind             = "Group"
	Group_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Group_Kind}.String()
	Group_KindAPIVersion   = Group_Kind + "." + CRDGroupVersion.String()
	Group_GroupVersionKind = CRDGroupVersion.WithKind(Group_Kind)
)

func init() {
	SchemeBuilder.Register(&Group{}, &GroupList{})
}
