apiVersion: nebraska.crossplane.io/v1alpha1
kind: Channel
metadata:
  annotations:
    meta.upbound.io/example-id: nebraska/v1alpha1/channel
  labels:
    testing.upbound.io/example-name: channel
  name: channel
spec:
  forProvider:
    arch: amd64
    name: custom-channel
    packageId: ${data.nebraska_package.package.id}
