name: utilitywarehouse/nebraska
resources:
    nebraska_channel:
        subCategory: ""
        description: A release channel that provides a particular package version.
        name: nebraska_channel
        title: nebraska_channel Resource - terraform-provider-nebraska
        examples:
            - name: channel
              manifest: |-
                {
                  "arch": "amd64",
                  "name": "custom-channel",
                  "package_id": "${data.nebraska_package.package.id}"
                }
              references:
                package_id: data.nebraska_package.package.id
        argumentDocs: {}
        importStatements: []
    nebraska_group:
        subCategory: ""
        description: A group provides a particular release channel to machines and controls various options that manage the update procedure.
        name: nebraska_group
        title: nebraska_group Resource - terraform-provider-nebraska
        examples:
            - name: group
              manifest: |-
                {
                  "channel_id": "${nebraska_channel.channel.id}",
                  "name": "custom-group"
                }
              references:
                channel_id: nebraska_channel.channel.id
              dependencies:
                nebraska_channel.channel: |-
                    {
                      "arch": "amd64",
                      "name": "custom-channel",
                      "package_id": "${data.nebraska_package.package.id}"
                    }
        argumentDocs:
            60 minutes: .
            "false": .
            policy_max_updates_per_period: . Defaults to 1 minutes.
            policy_office_hours: .
            policy_period_interval: . Defaults to 9999999.
            "true": .
        importStatements: []
    nebraska_package:
        subCategory: ""
        description: A versioned package of the application.
        name: nebraska_package
        title: nebraska_package Resource - terraform-provider-nebraska
        examples:
            - name: test
              manifest: |-
                {
                  "description": "Flatcar Container Linux 2191.5.0",
                  "filename": "flatcar_production_update.gz",
                  "flatcar_action": [
                    {
                      "sha256": "LIkAKVZY2EJFiwTmltiJZLFLA5xT/FodbjVgqkyF/y8="
                    }
                  ],
                  "hash": "r3nufcxgMTZaxYEqL+x2zIoeClk=",
                  "size": "465881871",
                  "type": "flatcar",
                  "url": "https://update.release.flatcar-linux.net/amd64-usr/2191.5.0/",
                  "version": "2191.5.0"
                }
        argumentDocs:
            all: .
            cat update.gz | openssl dgst -sha1 -binary | base64: .
            cat update.gz | openssl dgst -sha256 -binary | base64: .
            flatcar: .
        importStatements: []
